<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('code' => 'AD', 'name' => 'ANDORRA'),
            array('code' => 'AE', 'name' => 'EMIRATOS ARABES UNIDOS'),
            array('code' => 'AF', 'name' => 'AFGHANISTAN'),
            array('code' => 'AG', 'name' => 'ANTIGUA Y BARBUDA'),
            array('code' => 'AI', 'name' => 'ANGUILLA'),
            array('code' => 'AL', 'name' => 'ALBANIA'),
            array('code' => 'AM', 'name' => 'ARMENIA'),
            array('code' => 'AO', 'name' => 'ANGOLA'),
            array('code' => 'AP', 'name' => 'ASIA / REGION PACIFICO'),
            array('code' => 'AQ', 'name' => 'ANTARCTICA'),
            array('code' => 'AR', 'name' => 'ARGENTINA'),
            array('code' => 'AS', 'name' => 'AMERICAN SAMOA'),
            array('code' => 'AT', 'name' => 'AUSTRIA'),
            array('code' => 'AU', 'name' => 'AUSTRALIA'),
            array('code' => 'AW', 'name' => 'ARUBA'),
            array('code' => 'AX', 'name' => 'ALAND ISLANDS'),
            array('code' => 'AZ', 'name' => 'AZERBAIJAN'),
            array('code' => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA'),
            array('code' => 'BB', 'name' => 'BARBADOS'),
            array('code' => 'BD', 'name' => 'BANGLADESH'),
            array('code' => 'BE', 'name' => 'BELGICA'),
            array('code' => 'BF', 'name' => 'BURKINA FASO'),
            array('code' => 'BG', 'name' => 'BULGARIA'),
            array('code' => 'BH', 'name' => 'BAHRAIN'),
            array('code' => 'BI', 'name' => 'BURUNDI'),
            array('code' => 'BJ', 'name' => 'BENIN'),
            array('code' => 'BL', 'name' => 'SAINT BARTHELEMY'),
            array('code' => 'BM', 'name' => 'BERMUDA'),
            array('code' => 'BN', 'name' => 'BRUNEI DARUSSALAM'),
            array('code' => 'BO', 'name' => 'BOLIVIA'),
            array('code' => 'BQ', 'name' => 'BONAIR'),
            array('code' => 'BR', 'name' => 'BRASIL'),
            array('code' => 'BS', 'name' => 'BAHAMAS'),
            array('code' => 'BT', 'name' => 'BHUTAN'),
            array('code' => 'BW', 'name' => 'BOTSWANA'),
            array('code' => 'BY', 'name' => 'BELARUS'),
            array('code' => 'BZ', 'name' => 'BELICE'),
            array('code' => 'CA', 'name' => 'CANADA'),
            array('code' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS'),
            array('code' => 'CD', 'name' => 'CONG'),
            array('code' => 'CF', 'name' => 'REPUBLICA CENTRAL DE AFRICA'),
            array('code' => 'CG', 'name' => 'CONGO'),
            array('code' => 'CH', 'name' => 'SUIZA'),
            array('code' => 'CI', 'name' => 'COTE D\'IVOIRE'),
            array('code' => 'CK', 'name' => 'COOK ISLANDS'),
            array('code' => 'CL', 'name' => 'CHILE'),
            array('code' => 'CM', 'name' => 'CAMERUN'),
            array('code' => 'CN', 'name' => 'CHINA'),
            array('code' => 'CO', 'name' => 'COLOMBIA'),
            array('code' => 'CR', 'name' => 'COSTA RICA'),
            array('code' => 'CU', 'name' => 'CUBA'),
            array('code' => 'CV', 'name' => 'CABO VERDE'),
            array('code' => 'CW', 'name' => 'CURACAO'),
            array('code' => 'CX', 'name' => 'ISLAS DE PASCUA'),
            array('code' => 'CY', 'name' => 'CHIPRE'),
            array('code' => 'CZ', 'name' => 'REPUBLICA CHECA'),
            array('code' => 'DE', 'name' => 'ALEMANIA'),
            array('code' => 'DIGO', 'name' => 'NOMBRE'),
            array('code' => 'DJ', 'name' => 'DJIBOUTI'),
            array('code' => 'DK', 'name' => 'DINAMARCA'),
            array('code' => 'DM', 'name' => 'DOMINICA'),
            array('code' => 'DO', 'name' => 'REPUBLICA DOMINICANA'),
            array('code' => 'DZ', 'name' => 'ALGERIA'),
            array('code' => 'EC', 'name' => 'ECUADOR'),
            array('code' => 'EE', 'name' => 'ESTONIA'),
            array('code' => 'EG', 'name' => 'EGIPTO'),
            array('code' => 'EH', 'name' => 'WESTERN SAHARA'),
            array('code' => 'ER', 'name' => 'ERITREA'),
            array('code' => 'ES', 'name' => 'ESPAÑA'),
            array('code' => 'ET', 'name' => 'ETIOPIA'),
            array('code' => 'FI', 'name' => 'FINLANDIA'),
            array('code' => 'FJ', 'name' => 'FIJI'),
            array('code' => 'FK', 'name' => 'ISLAS (MALVINAS)'),
            array('code' => 'FM', 'name' => 'MICRONESI'),
            array('code' => 'FO', 'name' => 'FAROE ISLANDS'),
            array('code' => 'FR', 'name' => 'FRANCIA'),
            array('code' => 'GA', 'name' => 'GABON'),
            array('code' => 'GB', 'name' => 'REINO UNIDO'),
            array('code' => 'GD', 'name' => 'GRANADA'),
            array('code' => 'GE', 'name' => 'GEORGIA'),
            array('code' => 'GF', 'name' => 'GUYANA FRANCESA'),
            array('code' => 'GG', 'name' => 'GUERNSEY'),
            array('code' => 'GH', 'name' => 'GANA'),
            array('code' => 'GI', 'name' => 'GIBRALTAR'),
            array('code' => 'GL', 'name' => 'GROENLANDIA'),
            array('code' => 'GM', 'name' => 'GAMBIA'),
            array('code' => 'GN', 'name' => 'GUINEA'),
            array('code' => 'GP', 'name' => 'GUADELOUPE'),
            array('code' => 'GQ', 'name' => 'GUINEA ECUATORIAL'),
            array('code' => 'GR', 'name' => 'GRECIA'),
            array('code' => 'GS', 'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'),
            array('code' => 'GT', 'name' => 'GUATEMALA'),
            array('code' => 'GU', 'name' => 'GUAM'),
            array('code' => 'GW', 'name' => 'GUINEA-BISSAU'),
            array('code' => 'GY', 'name' => 'GUYANA'),
            array('code' => 'HN', 'name' => 'HONDURAS'),
            array('code' => 'HR', 'name' => 'CROACIA'),
            array('code' => 'HT', 'name' => 'HAITI'),
            array('code' => 'HU', 'name' => 'HUNGRIA'),
            array('code' => 'ID', 'name' => 'INDONESIA'),
            array('code' => 'IE', 'name' => 'IRLANDA'),
            array('code' => 'IL', 'name' => 'ISRAEL'),
            array('code' => 'IM', 'name' => 'ISLE OF MAN'),
            array('code' => 'IN', 'name' => 'INDIA'),
            array('code' => 'IO', 'name' => 'BRITISH INDIAN OCEAN TERRITORY'),
            array('code' => 'IQ', 'name' => 'IRAQ'),
            array('code' => 'IR', 'name' => 'IRA'),
            array('code' => 'IS', 'name' => 'ISLANDIA'),
            array('code' => 'IT', 'name' => 'ITALIA'),
            array('code' => 'JE', 'name' => 'JERSEY'),
            array('code' => 'JM', 'name' => 'JAMAICA'),
            array('code' => 'JO', 'name' => 'JORDAN'),
            array('code' => 'JP', 'name' => 'JAPAN'),
            array('code' => 'KE', 'name' => 'KENYA'),
            array('code' => 'KG', 'name' => 'KYRGYZSTAN'),
            array('code' => 'KH', 'name' => 'CAMBOYA'),
            array('code' => 'KI', 'name' => 'KIRIBATI'),
            array('code' => 'KM', 'name' => 'COMOROS'),
            array('code' => 'KN', 'name' => 'SAINT KITTS AND NEVIS'),
            array('code' => 'KR', 'name' => 'KORE'),
            array('code' => 'KW', 'name' => 'KUWAIT'),
            array('code' => 'KY', 'name' => 'ISLAS CAIMAN'),
            array('code' => 'KZ', 'name' => 'KAZAKHSTAN'),
            array('code' => 'LA', 'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC'),
            array('code' => 'LB', 'name' => 'LEBANON'),
            array('code' => 'LC', 'name' => 'SANTA LUCIA'),
            array('code' => 'LI', 'name' => 'LIECHTENSTEIN'),
            array('code' => 'LK', 'name' => 'SRI LANKA'),
            array('code' => 'LR', 'name' => 'LIBERIA'),
            array('code' => 'LS', 'name' => 'LESOTHO'),
            array('code' => 'LT', 'name' => 'LITHUANIA'),
            array('code' => 'LU', 'name' => 'LUXEMBOURG'),
            array('code' => 'LV', 'name' => 'LATVIA'),
            array('code' => 'LY', 'name' => 'LIBYA'),
            array('code' => 'MA', 'name' => 'MARRUECOS'),
            array('code' => 'MC', 'name' => 'MONACO'),
            array('code' => 'MD', 'name' => 'MOLDOV'),
            array('code' => 'ME', 'name' => 'MONTENEGRO'),
            array('code' => 'MF', 'name' => 'SAN MARTIN'),
            array('code' => 'MG', 'name' => 'MADAGASCAR'),
            array('code' => 'MH', 'name' => 'MARSHALL ISLANDS'),
            array('code' => 'MK', 'name' => 'MACEDONIA'),
            array('code' => 'ML', 'name' => 'MALI'),
            array('code' => 'MM', 'name' => 'MYANMAR'),
            array('code' => 'MN', 'name' => 'MONGOLIA'),
            array('code' => 'MO', 'name' => 'MACAU'),
            array('code' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS'),
            array('code' => 'MQ', 'name' => 'MARTINIQUE'),
            array('code' => 'MR', 'name' => 'MAURITANIA'),
            array('code' => 'MS', 'name' => 'MONTSERRAT'),
            array('code' => 'MT', 'name' => 'MALTA'),
            array('code' => 'MU', 'name' => 'MAURITIUS'),
            array('code' => 'MV', 'name' => 'MALDIVES'),
            array('code' => 'MW', 'name' => 'MALAWI'),
            array('code' => 'MX', 'name' => 'MEXICO'),
            array('code' => 'MY', 'name' => 'MALASIA'),
            array('code' => 'MZ', 'name' => 'MOZAMBIQUE'),
            array('code' => 'NA', 'name' => 'NAMIBIA'),
            array('code' => 'NC', 'name' => 'NUEVA CALEDONIA'),
            array('code' => 'NE', 'name' => 'NIGER'),
            array('code' => 'NF', 'name' => 'NORFOLK ISLAND'),
            array('code' => 'NG', 'name' => 'NIGERIA'),
            array('code' => 'NI', 'name' => 'NICARAGUA'),
            array('code' => 'NL', 'name' => 'HOLANDA, PAISES BAJOS'),
            array('code' => 'NO', 'name' => 'NORUEGA'),
            array('code' => 'NP', 'name' => 'NEPAL'),
            array('code' => 'NR', 'name' => 'NAURU'),
            array('code' => 'NU', 'name' => 'NIUE'),
            array('code' => 'NZ', 'name' => 'NUEVA ZELANDIA'),
            array('code' => 'OM', 'name' => 'OMAN'),
            array('code' => 'PA', 'name' => 'PANAMA'),
            array('code' => 'PE', 'name' => 'PERU'),
            array('code' => 'PF', 'name' => 'FRENCH POLYNESIA'),
            array('code' => 'PG', 'name' => 'PAPUA NEW GUINEA'),
            array('code' => 'PH', 'name' => 'FILIPINAS'),
            array('code' => 'PK', 'name' => 'PAKISTAN'),
            array('code' => 'PL', 'name' => 'POLONIA'),
            array('code' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON'),
            array('code' => 'PN', 'name' => 'PITCAIRN ISLANDS'),
            array('code' => 'PR', 'name' => 'PUERTO RICO'),
            array('code' => 'PS', 'name' => 'PALESTINA'),
            array('code' => 'PT', 'name' => 'PORTUGAL'),
            array('code' => 'PW', 'name' => 'PALAU'),
            array('code' => 'PY', 'name' => 'PARAGUAY'),
            array('code' => 'QA', 'name' => 'QATAR'),
            array('code' => 'RE', 'name' => 'REUNION'),
            array('code' => 'RO', 'name' => 'ROMANIA'),
            array('code' => 'RS', 'name' => 'SERBIA'),
            array('code' => 'RU', 'name' => 'RUSIA'),
            array('code' => 'RW', 'name' => 'RUANDA'),
            array('code' => 'SA', 'name' => 'ARABIA SAUDITA'),
            array('code' => 'SB', 'name' => 'ISLAS SALOMON'),
            array('code' => 'SC', 'name' => 'SEYCHELLES'),
            array('code' => 'SD', 'name' => 'SUDAN'),
            array('code' => 'SE', 'name' => 'SUECIA'),
            array('code' => 'SG', 'name' => 'SINGAPUR'),
            array('code' => 'SH', 'name' => 'SAINT HELENA'),
            array('code' => 'SI', 'name' => 'ESLOVENIA'),
            array('code' => 'SJ', 'name' => 'SVALBARD AND JAN MAYEN'),
            array('code' => 'SK', 'name' => 'ESLOVAQUIA'),
            array('code' => 'SL', 'name' => 'SIERRA LEONE'),
            array('code' => 'SM', 'name' => 'SAN MARINO'),
            array('code' => 'SN', 'name' => 'SENEGAL'),
            array('code' => 'SO', 'name' => 'SOMALIA'),
            array('code' => 'SR', 'name' => 'SURINAM'),
            array('code' => 'SS', 'name' => 'SUDAN DEL SUR'),
            array('code' => 'ST', 'name' => 'SAO TOME AND PRINCIPE'),
            array('code' => 'SV', 'name' => 'EL SALVADOR'),
            array('code' => 'SX', 'name' => 'SINT MAARTEN (DUTCH PART)'),
            array('code' => 'SY', 'name' => 'SIRIA REPUBLICA ARABE'),
            array('code' => 'SZ', 'name' => 'SWAZILAND'),
            array('code' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS'),
            array('code' => 'TD', 'name' => 'CHAD'),
            array('code' => 'TG', 'name' => 'TOGO'),
            array('code' => 'TH', 'name' => 'TAILANDIA'),
            array('code' => 'TJ', 'name' => 'TAJIKISTAN'),
            array('code' => 'TK', 'name' => 'TOKELAU'),
            array('code' => 'TL', 'name' => 'TIMOR-LESTE'),
            array('code' => 'TM', 'name' => 'TURKMENISTAN'),
            array('code' => 'TN', 'name' => 'TUNISIA'),
            array('code' => 'TO', 'name' => 'TONGA'),
            array('code' => 'TR', 'name' => 'TURQUIA'),
            array('code' => 'TT', 'name' => 'TRINIDAD Y TOBAGO'),
            array('code' => 'TV', 'name' => 'TUVALU'),
            array('code' => 'TW', 'name' => 'TAIWAN'),
            array('code' => 'TZ', 'name' => 'TANZANIA'),
            array('code' => 'UA', 'name' => 'UCRANIA'),
            array('code' => 'UG', 'name' => 'UGANDA'),
            array('code' => 'UM', 'name' => 'UNITED STATES MINOR OUTLYING ISLANDS'),
            array('code' => 'US', 'name' => 'ESTADOS UNIDOS'),
            array('code' => 'UY', 'name' => 'URUGUAY'),
            array('code' => 'UZ', 'name' => 'UZBEKISTAN'),
            array('code' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)'),
            array('code' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES'),
            array('code' => 'VE', 'name' => 'VENEZUELA'),
            array('code' => 'VG', 'name' => 'VIRGIN ISLAND'),
            array('code' => 'VN', 'name' => 'VIETNAM'),
            array('code' => 'VU', 'name' => 'VANUATU'),
            array('code' => 'WF', 'name' => 'WALLIS AND FUTUNA'),
            array('code' => 'WS', 'name' => 'SAMOA'),
            array('code' => 'YE', 'name' => 'YEMEN'),
            array('code' => 'YT', 'name' => 'MAYOTTE'),
            array('code' => 'ZA', 'name' => 'SUDAFRICA'),
            array('code' => 'ZM', 'name' => 'ZAMBIA'),
            array('code' => 'ZW', 'name' => 'ZIMBABWE')
        );

        Country::insert($countries);
    }
}
